### ISSUE TITLE
Can you add a colab script to launch an app similar to the hugging face playground?

### ISSUE THREAD

**Issue by sdes21** [Lightricks/LTX-Video#21]
Would love to try it on the google colab pro gpus.

**Comment by LuthandoMaqondo** [comment]
I've added a Notebook last night:
https://github.com/LuthandoMaqondo/LTX-Video/tree/luthando-contribution

**Comment by maneeshkush** [comment]
Traceback (most recent call last):
  File "/content/LTX-Video/inference1.py", line 444, in <module>
    main()
  File "/content/LTX-Video/inference1.py", line 306, in main
    vae = load_vae(vae_dir)
          ^^^^^^^^^^^^^^^^^
  File "/content/LTX-Video/inference1.py", line 37, in load_vae
    vae = CausalVideoAutoencoder.from_config(vae_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/LTX-Video/ltx_video/models/autoencoders/causal_video_autoencoder.py", line 65, in from_config
    config["_class_name"] == "CausalVideoAutoencoder"
AssertionError: config must have
