### ISSUE TITLE
text_encoder should be unloaded from cuda to reduce vram usage after text encoding finished

### ISSUE THREAD

**Issue by leo212** [Lightricks/LTX-Video#30]
https://github.com/Lightricks/LTX-Video/blob/a01a171f8fe3d99dce2728d60a73fecf4d4238ae/ltx_video/pipelines/pipeline_ltx_video.py#L878

After running encode_prompt, there should be :
```
self.text_encoder.to("cpu")      
torch.cuda.empty_cache()
```
otherwise the next steps may crash with OOM on devices with low memory, when it actually doesn't need that amount of memory to run.
adding this line will allow the model to even run on 8GB VRAM.

**Comment by luthandomaqondo-95** [comment]
Great point, someone has made a PR for this and is now waiting for the Merge.

**Comment by nitinmukesh** [comment]
@leo212  @luthandomaqondo-95 

I merged the PR changes locally, still 16 GB of memory
![image](https://github.com/user-attachments/assets/27afb87b-9e91-4ef9-b731-706265e086cb)

**Comment by leo212** [comment]
Thank you. even if it needs 13.8 it is now much efficient than before (required more than 20GB).
when I used it with bfloat16 it consumed even less (about 9GB).

**Comment by nitinmukesh** [comment]
I am working to make it work on as low as 6 GB VRAM + 12 GB shared.

**Comment by hprsnc** [comment]
No matter what I try on my RTX 3060 and even with these two lines added, I'm getting an out-of-memory error.

```
(venv) user@Monster:~/git/LTX-Video$ python inference.py --ckpt_path ./models/ltx-video-2b-v0.9.1.safetensors --prompt "$(cat prompt.txt)" --height 720 --width 1280 --num_frames 17 --seed 0 --offload_to_cpu
Running generation with arguments: Namespace(ckpt_path='./models/ltx-video-2b-v0.9.1.safetensors', input_video_path=None, input_image_path=None, output_path=None, seed=0, num_inference_steps=40, num_images_per_prompt=1, guidance_scale=3, stg_scale=1, stg_rescale=0.7, stg_mode='stg_a', stg_skip_layers='19', image_cond_noise_scale=0.15, height=720, width=1280, num_frames=17, frame_rate=25, precision='bfloat16', decode_timestep=0.05, decode_noise_scale=0.025, prompt='Some prompt here.', negative_prompt='worst quality, inconsistent motion, blurry, jittery, distorted', offload_to_cpu=True)
Padded dimensions: 736x1280x17
Downloading shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 19878.22it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 17.65it/s]
Traceback (most recent call last):
  File "/home/user/git/LTX-Video/inference.py", line 488, in <module>
    main()
  File "/home/user/git/LTX-Video/inference.py", line 342, in main
    text_encoder = text_encoder.cuda()
  File "/home/user/git/LTX-Video/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3124, in cuda
    return super().cuda(*args, **kwargs)
  File "/home/user/git/LTX-Video/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1050, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/git/LTX-Video/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/home/user/git/LTX-Video/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/home/user/git/LTX-Video/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/home/user/git/LTX-Video/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in _apply
    param_applied = fn(param)
  File "/home/user/git/LTX-Video/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1050, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 160.00 MiB. GPU 0 has a total capacity of 11.75 GiB of which 10.69 MiB is free. Including non-PyTorch memory, this process has 11.74 GiB memory in use. Of the allocated memory 11.58 GiB is allocated by PyTorch, and 54.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
