### ISSUE TITLE
'UNetMidBlock3D' object has no attribute 'downsample'

### ISSUE THREAD

**Issue by patientx** [Lightricks/LTX-Video#75]
Using the default i2v workflow, with 0.9.1 model. 

```
!!! Exception during processing !!! 'UNetMidBlock3D' object has no attribute 'downsample'
Traceback (most recent call last):
  File "D:\c2\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\c2\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\c2\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\c2\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\c2\custom_nodes\ComfyUI-LTXVideo\transformer.py", line 164, in configure_sizes
    latent_shape, latent_frame_rate = self.latent_shape_and_frame_rate(
  File "D:\c2\custom_nodes\ComfyUI-LTXVideo\transformer.py", line 124, in latent_shape_and_frame_rate
    video_scale_factor, vae_scale_factor, _ = get_vae_size_scale_factor(
  File "D:\c2\venv\lib\site-packages\ltx_video\models\autoencoders\vae_encode.py", line 173, in get_vae_size_scale_factor
    [
  File "D:\c2\venv\lib\site-packages\ltx_video\models\autoencoders\vae_encode.py", line 176, in <listcomp>
    if isinstance(block.downsample, Downsample3D)
  File "D:\c2\venv\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'UNetMidBlock3D' object has no attribute 'downsample'
```

**Comment by Creepybits** [comment]
I have this error as well, but only when I tried the fp8 checkpoint. The large is still working fine.

**Comment by patientx** [comment]
> I have this error as well, but only when I tried the fp8 checkpoint. The large is still working fine.

I am using the "ltx-video-2b-v0.9.1.safetensors" dunno there is a fp8 model out there , wonder if that helps with speed.

**Comment by Kwisss** [comment]
the gguf model also throws this error

**Comment by pkrasicki** [comment]
I'm also getting this when trying to use the gguf version with the provided workflow.

**Comment by patientx** [comment]
I get this with the default model and I only get this with this nodes , with comfyui's implementation there is no error with any models.

**Comment by re3me** [comment]
Same issue here.

**Comment by Niutonian** [comment]
Using the gguf, any solutions?
