### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'vae/config.json'

### ISSUE THREAD

**Issue by anelder-human** [Lightricks/LTX-Video#83]
I'm hoping someone can point me in the direction so that I can work out why LTX is failing for me:

```
python inference.py --ckpt_path . --input_image_path ./kai.png --height 720 --width 1024 --num_frames 100 --seed 2046
Running generation with arguments: Namespace(ckpt_path='.', input_video_path=None, input_image_path='./kai.png', output_path=None, seed=2046, num_inference_steps=40, num_images_per_prompt=1, guidance_scale=3, stg_scale=1, stg_rescale=0.7, stg_mode='stg_a', stg_skip_layers='19', image_cond_noise_scale=0.15, height=720, width=1024, num_frames=100, frame_rate=25, precision='bfloat16', decode_timestep=0.05, decode_noise_scale=0.025, prompt=None, negative_prompt='worst quality, inconsistent motion, blurry, jittery, distorted', offload_to_cpu=False)
Padded dimensions: 736x1024x105
Traceback (most recent call last):
  File "/workspace/LTX-Video/inference.py", line 488, in <module>
    main()
  File "/workspace/LTX-Video/inference.py", line 327, in main
    vae = CausalVideoAutoencoder.from_pretrained(ckpt_path)
  File "/workspace/LTX-Video/ltx_video/models/autoencoders/causal_video_autoencoder.py", line 75, in from_pretrained
    with open(config_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'vae/config.json'
```
Something wrong during install or something I'm missing in the instructions perhaps? Any pointer appreciated since this is non-obvious to me.

**Comment by anelder-human** [comment]
Just to note that I finally got this working via following the diffusers instructions for inference i.e.  https://huggingface.co/docs/diffusers/main/en/api/pipelines/ltx_video

**Comment by euwern** [comment]
LTX works on huggingface repo but not in original repo (this repo). 
I have a hard time getting the inference script to run on my machine due to missing config and weight. 
I hope someone can share a script to download all necessary weights and config to get it working.
